### ISSUE TITLE
[Feature] Multiple Overlays and Overlay Selection

### ISSUE THREAD

**Issue by TanmoySG** [TanmoySG/k-deploy-action#16]
A project/deployment might have multiple overlays, eg - prod, non-prod, etc. Add way to define the overlay names and their paths centrally and in the Action `with` section, some parameter like overlay or selectedOverlay to pick the overlay by name.

[Checkpoints]
- [ ] TBD

[Example]
```yml
- name: Kubernetes Deployment
  uses: TanmoySG/k-deploy-action@v0.2.2-alpha
  with:
    kubeconfig: path/to/kubeconfig
    namespace: 'default'
    kustomize: true
    overlays:
      - prod : deploy/overlays/prod
      - non-prod : deploy/overlays/non-prod
    overlay: prod
```

Something like this, or
```yml
- name: Kubernetes Deployment
  uses: TanmoySG/k-deploy-action@v0.2.2-alpha
  with:
    kubeconfig: path/to/kubeconfig
    namespace: 'default'
    kustomizations: 
      - prod : deploy/overlays/prod
      - non-prod : deploy/overlays/non-prod
    use: prod
```
